backend:
  name: gitlab
  repo: spyyderz/sjdg
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "about"
    name: "about"
    files:
      - name: "mission"
        file: "content/pages/about/mission.md"
        extension: "md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "constitution"
        file: "content/pages/about/constitution.md"
        extension: "md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "projects"
        file: "content/pages/about/projects.md"
        extension: "md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "support"
        file: "content/pages/about/support.md"
        extension: "md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
