backend:
  name: git-gateway
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "about"
    name: "about"
    folder: "content/about"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Published", name: "published", widget: "boolean", default: false, required: false}
      - {label: "Sort", name: "sort", widget: "number", default: 99}
  - label: "courses"
    name: "courses"
    folder: "content/courses"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Published", name: "published", widget: "boolean", default: false, required: false}
      - {label: "Sort", name: "sort", widget: "number", default: 99}
