backend:
  name: gitlab
  repo: spyyderz/sjdg
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "about"
    name: "about"
    files:
      - label: "mission"
        name: "mission"
        file: "content/pages/about/mission.md"
        extension: "md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
